// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21:57:18 30/6/2025
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/composables/**/*.{js,ts,mjs}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/utils/**/*.{js,ts,mjs}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/WINDOWS/Desktop/WorkSpace/clothes-ercom/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;